# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-qd8N-qdWiW_4qenV-f02bUiW_iAfuzt
"""


import pandas as pd
import numpy as np
import pytz
from datetime import datetime

lead_logs = pd.read_csv("data/lead_log.csv")
user_referrals = pd.read_csv("data/user_referrals.csv")
user_referral_logs = pd.read_csv("data/user_referral_logs.csv")
user_logs = pd.read_csv("data/user_logs.csv")
user_referral_statuses = pd.read_csv("data/user_referral_statuses.csv")
referral_rewards = pd.read_csv("data/referral_rewards.csv")
paid_transactions = pd.read_csv("data/paid_transactions.csv")

def profile_table(df, table_name):

    profile = pd.DataFrame({
        "table_name": table_name,
        "column_name": df.columns,
        "data_type": df.dtypes.values,
        "null_count": df.isnull().sum().values,
        "distinct_count": df.nunique().values
    })

    return profile

profiles = pd.concat([
    profile_table(lead_logs, "lead_logs"),
    profile_table(user_referrals, "user_referrals"),
    profile_table(user_referral_logs, "user_referral_logs"),
    profile_table(user_logs, "user_logs"),
    profile_table(user_referral_statuses, "user_referral_statuses"),
    profile_table(referral_rewards, "referral_rewards"),
    profile_table(paid_transactions, "paid_transactions")
])

profiles.to_csv("profiling_results.csv", index=False)
profiles.head()

user_referrals["referral_at"] = pd.to_datetime(user_referrals["referral_at"], utc=True)
user_referrals["updated_at"] = pd.to_datetime(user_referrals["updated_at"], utc=True)

paid_transactions["transaction_at"] = pd.to_datetime(paid_transactions["transaction_at"], utc=True)

user_logs["membership_expired_date"] = pd.to_datetime(
    user_logs["membership_expired_date"], utc=True
)

user_referrals = user_referrals.dropna(subset=["referral_id"])

user_logs["name"] = user_logs["name"].str.title()
user_referrals["referee_name"] = user_referrals["referee_name"].str.title()

user_referral_logs_df = user_referral_logs.rename(columns={'id': 'user_referral_log_id'})
user_logs_df = user_logs.rename(columns={'id': 'user_log_id'})
referral_rewards_df = referral_rewards.rename(columns={'id': 'reward_pk_id'}) # Renaming to avoid conflict with referral_reward_id in user_referrals
user_referral_statuses_df = user_referral_statuses.rename(columns={'id': 'status_pk_id'}) # Renaming to avoid conflict with user_referral_status_id in user_referrals


df = user_referrals.merge(
    user_referral_logs_df,
    left_on="referral_id",
    right_on="user_referral_id",
    how="left"
)

df = df.merge(
    user_logs_df,
    left_on="referrer_id",
    right_on="user_id",
    how="left"
)

df = df.merge(
    referral_rewards_df,
    left_on="referral_reward_id",
    right_on="reward_pk_id",
    how="left"
)

df = df.merge(
    paid_transactions,
    on="transaction_id",
    how="left"
)

df = df.merge(
    user_referral_statuses_df,
    left_on="user_referral_status_id",
    right_on="status_pk_id",
    how="left"
)

lead_logs_df = lead_logs.rename(columns={'id': 'lead_log_id', 'created_at': 'lead_log_created_at'})
df = df.merge(
    lead_logs_df,
    left_on="referee_id",
    right_on="lead_id",
    how="left"
)

def get_source_category(row):

    if row["referral_source"] == "User Sign Up":
        return "Online"

    elif row["referral_source"] == "Draft Transaction":
        return "Offline"

    elif row["referral_source"] == "Lead":
        return row["source_category"]

    else:
        return "Unknown"


df["referral_source_category"] = df.apply(get_source_category, axis=1)

def validate_referral(row):

    if (
        row["reward_value"] > 0
        and row["description"] == "Berhasil"
        and row["transaction_status"] == "PAID"
        and row["transaction_type"] == "NEW"
        and row["transaction_at"] > row["referral_at"]
        and row["membership_expired_date"] > row["referral_at"]
        and row["is_deleted"] == False
        and row["is_reward_granted"] == True
    ):
        return True

    return False

# Ensure the column is string type before applying .str operations
df["reward_value"] = df["reward_value"].astype(str).str.replace(" days", "", regex=False)
# Convert to numeric, coerce errors to NaN, fill NaN with 0, then convert to int
df["reward_value"] = pd.to_numeric(df["reward_value"], errors='coerce').fillna(0).astype(int)
df["is_business_logic_valid"] = df.apply(validate_referral, axis=1)

report = df[[
    "referral_id",
    "referral_source",
    "referral_source_category",
    "referral_at",
    "referrer_id",
    "name",
    "phone_number",
    "homeclub",
    "referee_id",
    "referee_name",
    "referee_phone",
    "description",
    "reward_value",
    "transaction_id",
    "transaction_status",
    "transaction_at",
    "transaction_location",
    "transaction_type",
    "updated_at",
    "is_business_logic_valid"
]]

report.to_csv("referral_report.csv", index=False)

